spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: email4testdeveloper@gmail.com
    password: rfelqpuasbktrbqn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
